// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYGm3N86DKpsUa6TFshHiWg6PIs77OCw',
    appId: '1:427619490984:web:f96343686b25a98e1e769d',
    messagingSenderId: '427619490984',
    projectId: 'project-integra',
    authDomain: 'project-integra.firebaseapp.com',
    storageBucket: 'project-integra.firebasestorage.app',
    measurementId: 'G-YF6PRWQJKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsDXSrzCPYbUVqDNQjIF0ZK0REbh9aPc',
    appId: '1:427619490984:android:27230246a17ce70e1e769d',
    messagingSenderId: '427619490984',
    projectId: 'project-integra',
    storageBucket: 'project-integra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBoS5GlNkdvlOcA8qcE-TtxVOadWyjwEU',
    appId: '1:427619490984:ios:7b19bb8abea20cdc1e769d',
    messagingSenderId: '427619490984',
    projectId: 'project-integra',
    storageBucket: 'project-integra.firebasestorage.app',
    iosBundleId: 'com.example.projCompras',
  );
}
